### ISSUE TITLE
Call source.dispose on raster-sources when their layers are removed from a map

### ISSUE THREAD

**Issue by MichaelLangbein** [dlr-eoc/ukis-frontend-libraries#100]
## Describe the bug
I just red the discussion here regarding memory leaks in openlayers due to raster-sources: https://github.com/openlayers/openlayers/issues/10856

The gist of it seems to be that we, the user, need to make sure that a raster-source-worker is disposed of when we no longer need a source.
Citing:
 ```
If your application is creating many new sources over time (case 1), then it is the responsibility of your application to call source.dispose() when you no longer need an old source.
```

I don’t think that we already do this in ukis. 

## To Reproduce

I haven't created a reproduction yet, but wanted to document this potential problem in the form of an issue before it gets forgotten.
Theoretically, to reproduce the problem:

 - add a raster-source layer that uses webworkers (that is, one with `threads: >0`
 - remove it from the map
 - measure memory usage and note that the layer's memory has not been freed up

## Expected behavior
Openlayers does not seem to want to take responsibility for the webworker memory-management... so the expected behavior is for us, the application developers, to discard of webworkers when no longer required.

## Versions

 - "@angular/core": "~12.2.5",
 -  @dlr-eoc/xxxxx@8.0.0-next.2

**Comment by boeckMt** [comment]
We do not use [ol/source/Raster.js](https://github.com/openlayers/openlayers/blob/665da4743756a7778043accf7d125ac34a383515/src/ol/source/Raster.js) in the UKIS-Layers, see: https://github.com/dlr-eoc/ukis-frontend-libraries/blob/08538098a311dc8adcfd106a582bdc510e6e5117/projects/map-ol/src/lib/map-ol.service.ts#L723


this can only be the case for the `CustomLayer` Type.

**Comment by MichaelLangbein** [comment]
Perfect - I think that closes this issue then! Thanks a lot!
If it's alright with you, I'll just close this then.
