### ISSUE TITLE
"Getting started instructions": no longer compatible with angular-13 + clarity-12

### ISSUE THREAD

**Issue by MichaelLangbein** [dlr-eoc/ukis-frontend-libraries#101]
## Describe the bug
The [getting started section](https://github.com/dlr-eoc/ukis-frontend-libraries#getting-started-setup-a-new-ukis-client) of our documentation describes how to set up a ukis project. Unfortunately, the current version of angular (13) and the current version of @clr/angular (12) are not compatible with each other

## To Reproduce
```bash
ng new proj
cd proj
ng add @clr/angular
```

Yields error message:
```bash
‼ Unable to find compatible package.  Using 'latest' tag.
‼ Package has unmet peer dependencies. Adding the package may not succeed.

The package @clr/angular@12.0.7 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: clarityex@0.0.0
npm ERR! Found: @angular/common@13.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from @clr/angular@12.0.7
npm ERR! node_modules/@clr/angular
npm ERR!   @clr/angular@"12.0.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\lang_m13\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lang_m13\AppData\Local\npm-cache\_logs\2021-11-15T10_49_26_348Z-debug.log
× Package install failed, see above.
```

## Expected behavior
We should either document that we currently require angular 12, or update ukis to use the latest version of clarity (probably with webcomponents only).

## Versions

**App**

* Angular: @angular/common@13.0.1
* Node: v.16.13.0
* Clarity: @clr/angular@12.0.7
* UKIS: not yet installed at this point of the reproduction

**Comment by boeckMt** [comment]
This is because you're trying to use Angular 13 with a Clarity Version for Angular 12.

If you create a new project with Angular 12 it should work.

Maybe we could update the Readme so that the user knows that he should use the same Angular Version like we do.
