### ISSUE TITLE
Show attributions for Vector Layers

### ISSUE THREAD

**Issue by MichaelLangbein** [dlr-eoc/ukis-frontend-libraries#119]
## Description
`VectorLayer`s have the property `attribution`, but it is not displayed on the map.

* What is missing? It would be nice to add an attribution to a vector-dataset.
* What is it useful for? Many datasets are served from our application, but stem from a third party.
* Does this change impact existing behaviors? If so how? No.

## Relevant Package
This feature request is for [@dlr-eoc/map-ol](https://github.com/dlr-eoc/ukis-frontend-libraries/packages)
Or if it is not fitting anywhere then a new @dlr-eoc/<name>

## Examples
In `route-example-layers/route-map.component.ts` add an attribution to the layer `GeoJSON Vector Layer`. It's not shown on the map.

### Describe alternatives you've considered
We can add an attribution to the `actions`, but that would not be visible on the map.

**Comment by boeckMt** [comment]
If this is done it should work.

> /** TODO: adjust this so it can be generally used for all layers */

https://github.com/dlr-eoc/ukis-frontend-libraries/blob/d28dbc18495693c8711db4303c2a93d2857881ef/projects/map-ol/src/lib/map-ol.service.ts#L763


Meanwhile you could use a custom layer.
