### ISSUE TITLE
Allow Map OL Popup to pass an Angular Component

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#14]
## Description

Allow to pass a Angular Component in the layer popup so a user can create custom content in popups.

## Relevant Package
This feature request is for [@dlr-eoc/....](https://github.com/dlr-eoc/ukis-frontend-libraries/packages)
- @dlr-eoc/services-layers
- @dlr-eoc/map-ol

**Comment by boeckMt** [comment]
This more complicated than thought because we now pass an HTML element to the openlayers ol/Overlay and we first need to figure out how to pass a component or convert it.

**Comment by boeckMt** [comment]
**Workaround:** It is possible to pass an [angular element](https://angular.io/guide/elements) tag as html string which is then rendered by the browser as a custom element.

1. Create your component e.g.  `<TestComponent>` which should be used in the Popup.
2.  Add the TestComponent in the module's entryComponents list, to exclude it from compilation and avoid startup warnings or errors.
```ts
@NgModule({
  ...
  bootstrap: [AppComponent],
  entryComponents: [TestComponent],
})
export class AppModule { }
```

3. Convert the TestComponent to a custom element in the component's constructor of the angular component which is using it e.g. AppComponent.

```ts
...
constructor(injector: Injector) {
    // Convert `Component` to a custom element.
    const TestElement = createCustomElement(TestComponent, { injector });
    // Register the custom element with the browser.
    customElements.define('my-test-comp', TestElement);
  }
```

**Comment by MichaelLangbein** [comment]
Hey guys!

I created a little demo on how we could handle this issue: https://github.com/MichaelLangbein/demo_angular_ol_popup

The basic idea is: 
 - in the map-component, add an html-element that will serve as our ViewContainer.
 - on click into the map, dynamically create an angular-component and attach it to the view-container.
 - get the new element's native element, and add it to a new openlayers-overlay
 - add that overlay to the map.

Adding the native element as an ol-overlay means that openlayers moves the new component out of our view-container and into ol's overlay-container. Remarkably, however, this does *not* mean that angular loses track of the component. In fact, as the demo shows, change-detection, services etc. still seem to work fine even with those new elements now inside another html-parent element.

What do you think, should I implement this in ukis?

**Comment by boeckMt** [comment]
Hey @MichaelLangbein,

the problem here is that we do not only have "single popups".

As now you can have multiple layers, one uses a move event where the popup is created once and added to the map, if it is existing it it will be reused otherwise a new element is created and added to the map. Your second layer uses a click event and only shows one popup at a time, but if on is clicked it will stay there even if you check the move layer. And then you could have another layer which uses multi popups, like @voinSR introduced in the beginning of our library, all open popups should be there if the other events are handled.

So to have all this stuff, we would have to add a element in map-ol which then creates new elements with ol-overlays for certain cases e.g. a angular directive which have to handle all the events like map-ol.component:
- click: https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/map-ol/src/lib/map-ol.component.ts#L396
- dblclick: https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/map-ol/src/lib/map-ol.component.ts#L402
- pointermove: https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/map-ol/src/lib/map-ol.component.ts#L408

All this is not handled im map-ol.service which dynamically creates and adds/removes html elements
- https://github.com/dlr-eoc/ukis-frontend-libraries/blob/9e5c81e8082514e1f07dda0405489c233a386846/projects/map-ol/src/lib/map-ol.service.ts#L1131
- https://github.com/dlr-eoc/ukis-frontend-libraries/blob/9e5c81e8082514e1f07dda0405489c233a386846/projects/map-ol/src/lib/map-ol.service.ts#L1115
- https://github.com/dlr-eoc/ukis-frontend-libraries/blob/9e5c81e8082514e1f07dda0405489c233a386846/projects/map-ol/src/lib/map-ol.service.ts#L1346

And we also have to check for performance in the move case, because this is something a hade to fix last time https://github.com/dlr-eoc/ukis-frontend-libraries/pull/50/commits/12f77a80dc333471be3ea6431a21e6bcbeed487f

**Comment by MichaelLangbein** [comment]
Hi!
Alright, the Christmas-vacation is over and as a special present I've been working on a few enhancements.

Please find the minimal-working-version here: https://github.com/MichaelLangbein/demo_angular_ol_popup


 - Allows to define what *popup-strategy* to use: `single-popup`, `one-per-click`, or `follow-cursor`.
 - When using `follow-cursor`, a [debounce time](https://rxjs-dev.firebaseapp.com/api/operators/debounceTime) can be specified to fine-tune app-performance
 - General architecture:
     - A global `PopupService` keeps track of what popups should be displayed and what strategy to use.
        - May be shared between multiple maps
     - A global `PopupComponent` ensures a uniform design for all popups in all UKIS-applications. It accepts an Angular-component as an `@Input` which is displayed in the popup-body
     - For each map-type (ol, three, ...) there is one `PopupContainerComponent`
         - It listens to the `PopupService` for state-changes, 
         - ... creates  Angular `PopupComponents`,
         - ... and binds these components to the map
            - ... which in the case of openlayers is done using `Overlays`
            - I haven't made a three-js specific popup container yet, but I'll create one when required.
 - All public methods have been documented with further details


Primary objectives in this design were
 - *clarity*
    - only three classes: `PopupService`, `PopupComponent` and `PopupContainerComponent`
    - Clear User-Interface: user needs to add a popup-container-component under the map and then only call `PopupSerive.onClick` or `PopupService.onPointerMove`
 - *reusability*
    - `PopupService` and `PopupComponent` are generic, only `PopupContainer` requires map-engine-specific code
 - *performance*
    - rxjs debouncing to reduce redraws. 
    - If you want to, we could even create Popups outside of `ngZone` to avoid change-detection (what's your opinion on that?)

I'd like to use this approach in UKIS. What do you guys think?
 - Did I fulfill all your requests?
 - Do you see any issues with this architecture?

**Comment by MichaelLangbein** [comment]
As an example: this is how I've set up the popup-service in the demo-application:

```[javascript]
  private initPopups(): void {
    // configure how to display popups
    this.popupService.setStrategy('single-popup');

    // notify service of clicks on features
    this.mapService.getMap().on('click', (evt: MapBrowserEvent) => {
      const lnf = this.getLayerAndFeatureForEvent(evt);
      if (lnf) {
        this.popupService.onClick(lnf.l.get('id'), lnf.f, evt.coordinate);
      }
    });

    // notify service of hovers over features
    this.popupService.setPointerMoveDebounceTime(30);
    this.mapService.getMap().on('pointermove', (evt: MapBrowserEvent) => {
      const lnf = this.getLayerAndFeatureForEvent(evt);
      if (lnf) {
        this.popupService.onPointerMove(lnf.l.get('id'), lnf.f, evt.coordinate);
      }
    });
  }
```

**Comment by MichaelLangbein** [comment]
One more thing!
I just noticed that you described that the popup-strategy can differ between layers. 
I could at first not imagine a case where we'd want something like that. 

But I created a version that does things on a per-layer base. You'll notice that there are no big differences in general structure: 
https://github.com/MichaelLangbein/demo_angular_ol_popup/tree/layerWise

**Comment by boeckMt** [comment]
Hello @MichaelLangbein thanks a lot for your many efforts!!


This strategy is very different from what we're using right now, so we have to check if it is possible to integrate something like this without creating too much breaking changes.


I like the Idea to use [`nativeElement` from `@ViewChild`](https://github.com/MichaelLangbein/demo_angular_ol_popup/blob/83ad8b66df97f44b05d3f56e7268efb1bc584507/src/app/components/popup-container/popup-container.component.ts#L80) for the `Overlay.element`, maybe it is possible to crete this from `resolveComponentFactory` without the need of a dummy container somewhere. Then we only had to change a little thing in the current implementation of `MapOlService`

```ts

// https://github.com/dlr-eoc/ukis-frontend-libraries/blob/9e5c81e8082514e1f07dda0405489c233a386846/projects/map-ol/src/lib/map-ol.service.ts#L1444
...
private createPopupContainer(overlay: olOverlay, args: IPopupArgs, popupObj: any, html?: string, event?: 'click' | 'move') {
    let content = document.createElement('div');
    content.className = 'ol-popup-content';
    let popupHtml = '';
    if (args.popupFn) {
      popupHtml = args.popupFn(popupObj);
    }else if(args.popupComp){
     content = ... nativeElement;
    }
....
```

I think to define the pop up on the layer and all its possibilities (also different per Layer) is really useful so you can fine tune the behaviour based on the data of the layer.


Further I recognized some Issue which we already had and fixed in our current implementation:
- Popups are not removed if you are outside of the features or the map
- on move (follow-cursor) the popup should not have a Closer
- if you are on the same Feature the popup should not rerender


I also tried to create a simple `bodyComponent` in your example which only binds the properties in the template but then we get a `ExpressionChangedAfterItHasBeenCheckedError`.
This can be fixed when using something like 
```ts
// SimplePopupBodyComponent

@Input() set data(value: any) {
    if (value) {
      this.iProps = value;
      this.cd.detectChanges();
    }
  }

get props() {
    return this.iProps;  
}
...
```
but we should check if this could be handled internally.

**Comment by MichaelLangbein** [comment]
Hm, this is not easy. 
I need some time to do this...

**Comment by MichaelLangbein** [comment]
> I also tried to create a simple bodyComponent in your example which only binds the properties in the template but then we get a ExpressionChangedAfterItHasBeenCheckedError.

Can you tell me how I can reproduce that issue?

**Comment by MichaelLangbein** [comment]
> maybe it is possible to crete this from resolveComponentFactory without the need of a dummy container somewhere.

In the example you linked they actually *do* use a dummy-container: 
```js
document.getElementById('container').appendChild(newNode);
```
The purpose of `PopupContainerComponent` is to serve as a connection to angular's change-detection on one hand (just like the dummy-container in the linked example) but also to have a place where the popups that are currently on the ol-map are counted, so that they can easily be removed when no longer required. Of course, that logic could also be integrated into `MapOlComponent`, but I wanted to avoid cluttering that component even more. But I'm working on an example for how that could look.

**Comment by boeckMt** [comment]
>> bodyComponent in your example which only binds the properties in the template but then we get a ExpressionChangedAfterItHasBeenCheckedError.

> Can you tell me how I can reproduce that issue?

You can check it in this Example https://stackblitz.com/edit/github-u2ckco?file=src%2Fapp%2Fservices%2Fdata.service.ts

**Comment by MichaelLangbein** [comment]
Alright, thanks a lot for all the feedback! And most of all thanks for the link to creating dynamic components with out a `ViewContainerRef`!
I've tried to minimize changes to the existing framework, and I think that has worked quite well - please find the PR [here](https://github.com/dlr-eoc/ukis-frontend-libraries/pull/63).

**Comment by MichaelLangbein** [comment]
Alright, thanks a lot @boeckMt for all the hard work! Closing the issue now with PR [63](https://github.com/dlr-eoc/ukis-frontend-libraries/pull/63)
