### ISSUE TITLE
Layer-control: Deactivating sorting for layer control elements

### ISSUE THREAD

**Issue by lucas-angermann** [dlr-eoc/ukis-frontend-libraries#179]
## Description
At the moment there is no possibility to deactivate the sorting inside a `<ukis-layer-control>` element, e.g. inside 'Layers'. Inside `<ukis-base-layer-control>` there is no sorting, but there is only one layer allowed at a time. The proposed behavior would be to insert an optional flag to a `<ukis-layer-control>` element, which deactivates both the sorting per dag and drop and with the arrow buttons. 
e.g. 
```
<ukis-layer-control [sort]="false" [layersSvc]="layerSvc" [mapStateSvc]="mapStateSvc" [layerfilter]="'Overlays'">
</ukis-layer-control>
```
This change should not affect the existing behavior of the layer-control, but extend its functionality. 

## Relevant Package
This feature request is for [@dlr-eoc/layer-control](https://github.com/dlr-eoc/ukis-frontend-libraries/tree/main/projects/layer-control), especially this [layer-control template](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/main/projects/layer-control/src/lib/layer-control/layer-control.component.html#L1) and the [drop function](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/main/projects/layer-control/src/lib/layer-control/layer-control.component.ts#L54).

## Examples
The motivation for this change comes from the development of map-cesium. There the layer-control is used to handle 3D tile layers, which cannot be sorted. Therefore, the option to disable the sorting for the 3D layer area inside the layer control for the user would help to clarify the funcctionality of the 3D tiles layer control.

**Comment by boeckMt** [comment]
The sorting is done in [`cdkDropList`](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/d8d806a84ee72ad8b538354d1f32e5d29cdb3250/projects/layer-control/src/lib/layer-control/layer-control.component.html#LL1C6-L1C17).
Maybe a input `sorting: boolean` for `LayerControlComponent` and https://github.com/angular/components/blob/main/src/cdk/drag-drop/drag-drop.md#disabled-dragging should fix it.
