### ISSUE TITLE
Get native Layer (ol) from a UKIS-Layer

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#18]
## Description

Get the native layer (e.g. ol/layer/...) from the [ukis-layer](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/services-layers/src/lib/types/Layers.ts#L180) in the `LayersService`, so there is the possibility to work with the object reference of this layer later, so for some  use cases (like to trigger a change in the layer) all functionality of the native layer can be used and has not to be integrated in the generic 'ukis-layer'.

### Describe alternatives you've considered
As a workaround now we have to use a [CustomLayer](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/services-layers/src/lib/types/Layers.ts#L306) so we can get the `custom_layer` property back to use it.

## Relevant Package
This feature request is for [@dlr-eoc/....](https://github.com/dlr-eoc/ukis-frontend-libraries/packages)
- @dlr-eoc/services-layers
- @dlr-eoc/map-ol

**Comment by boeckMt** [comment]
I tried to create a basic implementation (which returns the new created layers to the Layerservice) for this but there are some API decisions to make:

The Layer could have an optional property e.g. 'nativeLayer' which gets assigned to the Layer on layer creation in them map component.
```ts
export class Layer implements ILayerOptions {
  name = '';
  id = '';
  ...
  /** the native layer from the mapping library: it should be assigned on layer creation in them map component e.g. map-ol  */
  nativeLayer?: any;
 ...
```

but we also have our `CustomLayer` which extends the Layer so we would have this native layer duplicated there.
```ts
export class CustomLayer extends Layer implements ICustomLayerOptions {
  type = 'custom';
  custom_layer: ICustomLayerOptions['custom_layer'] = {};
  ...
```

1. - [ ] Now we have the options to exclude the property on the `CustomLayer` ( Exclude<keyof T, K>>) 

2. - [ ] or maybe use the same property for both, but on the `CustomLayer` it is not optional.

The first would be the easiest but then we have to different names for the same layer `custom_layer` and `nativeLayer`.


The second would maybe bring a breaking change if we rename the property `custom_layer` and then there could also be some confusion for the User if he can add a nativeLayer to each layer, but for the User it should only be possible on the custom layer and for other layers it is more a private API. But if me make the API private it can only be set inside the Layer Class so we can not use it later on.

**Comment by MichaelLangbein** [comment]
Hm, nice!
I really need to look into this a little bit. But here's a spontaneous idea: instead of attaching a `native_layer` to the `Layer` once the `Layer` has been sent to (for example) `MapOl`, we could add a method to `MapOl`. Something like this:

```js
mapOl.getNativeLayer(layer: UkisLayer): OlLayer {...}
```

Advantage: If we add `native_layer` to `Layer`, the user does not know whether a `native_layer` has already been added to the `Layer` object. There might not (yet) be a `MapOl` (or `MapCesium`, `MapWordwind` etc). Or a `Layer` might even be displayed in multiple mapping backends - maybe an openlayers-map and a worldwind-map side by side. If we let the mapping-library return the native layer instead, these scenarios wouldn't be a problem.

**Comment by voinSR** [comment]
here are my 2 cents... do we actually need a custom layer? I think its intention was to work directly with web-map library layer types, so introducing the "native layer" type would exclude a need for a custom layer as the native layer can be customized to degree it allowed by the web-map library.

**Comment by boeckMt** [comment]
@MichaelLangbein we already have the the functionality `MapOlService.getLayerByKey({'id', layer.id})`
So this would be the same as `mapOl.getNativeLayer(layer: UkisLayer)`
But for the scenario with two maps side by side  you are right, then we would have a Problem!

@voinSR i think we need a possibility to use all functionality of the native layer from the mapping library, without implementing all this in our layer Types. This is was the `CustomLayer` was made for.

The intention of this Issue was to get the native layer (for non `CustomLayers`) more easily, without the use of `Map<XYZ>Service` but if we will have the scenario with multiple maps, than it is maybe more clear to use the maps service.
