### ISSUE TITLE
Update licenses route in demo-maps

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#19]
## Description

Update the licenses for the current dependencies used in demo maps and check how to do this automatically (e.g. on a new build of all libraries).

## Relevant Package
This feature request is for [@dlr-eoc/....](https://github.com/dlr-eoc/ukis-frontend-libraries/packages)
- demo-maps

**Comment by MichaelLangbein** [comment]
This issue has been discussed in the wake of PR #30 . While we have ultimately decided to not generate a `licenses.json` file for every build, documentation was added to guide the user in creating his own licenses-list based on the tool [dependency-check](https://www.npmjs.com/package/dependency-check).
