### ISSUE TITLE
Fixing the display of DataSources in map-cesium

### ISSUE THREAD

**Issue by lucas-angermann** [dlr-eoc/ukis-frontend-libraries#197]
## Describe the bug
At the moment DataSources like geoJSON or KML are not displayed correctly. There seems to be some interference with the handling of primitive datasets like tilesets.

## To Reproduce

1. Add UKIS VectorLayer of type geojson or kml
2. The data is not displayed on the cesium globe.

## Expected behavior
The VectorLayer is displayed correctly.

## Versions

**App**

* Angular: 14.2.11
* Node: v18.13.0
* Clarity: 13.17.0
* UKIS: 12.0.0-alpha.1

**Device:**
* chrome, edge, firefox

**Comment by boeckMt** [comment]
Thanks for that fix :)
