### ISSUE TITLE
Projection switch is broken

### ISSUE THREAD

**Issue by voinSR** [dlr-eoc/ukis-frontend-libraries#199]
## Describe the bug
After upgrading to v11.x and 12.x projection switch doesn't work. The browser's console shows a lot of errors thrown by OL and Proj. 

## To Reproduce

It seems the error is related to attempt map rendering outside of projection extent, e.g.  switch Arctic Polar Stereographic projection and try to pan the map below 60 deg lat.

it is also seen in the demo-maps

https://dlr-eoc.github.io/ukis-frontend-libraries/#/example-projection

## Expected behavior
projection switch without errors

## Versions

**App**

* UKIS: 12.0.0-alpha.1
* rest is the same as in the master branch

**Device:**
any

**Comment by voinSR** [comment]
ok, the problem is caused by wrong CRS defs in the projection switch demo map

**Comment by boeckMt** [comment]
Thanks for that fix :)
