### ISSUE TITLE
Update the main map libraries

### ISSUE THREAD

**Issue by lucas-angermann** [dlr-eoc/ukis-frontend-libraries#225]
## Description
The main map libraries using OpenLayers, CesiumJS and Maplibre should be updated to newer versions.
The update of major versions in the map dependencies can be regarded as breaking change and should therefore be done in one go.

## Relevant Package
This feature request is mainly for map-ol, map-cesium and map-maplibre but may require an update of other libraries as well.

**Comment by boeckMt** [comment]
### OpenLayers
- 7.3.0 to 8.0.0 https://github.com/openlayers/openlayers/blob/v8.0.0/changelog/upgrade-notes.md
- 8.0.0 to 9.0.0 https://github.com/openlayers/openlayers/releases/tag/v9.0.0

### Maplibre
- 4.1.3 to 4.5.0 https://github.com/maplibre/maplibre-gl-js/releases/tag/v4.5.0

### CesiumJS
- ...

**Comment by boeckMt** [comment]
Closes with https://github.com/dlr-eoc/ukis-frontend-libraries/pull/231
