### ISSUE TITLE
LayersService/updateLayer: ignores VectorLayers

### ISSUE THREAD

**Issue by MichaelLangbein** [dlr-eoc/ukis-frontend-libraries#51]
## Describe the bug
Calling `layersSvc.updateLayer(someVectorLayer)` has no effect. The reason is that `MapOlComponent.updateLayerParamsWith` has no case for VectorLayers.

## To Reproduce
A testcase has been set up in Route 3 (Events) of the demo-maps in the new branch `feature-update` (https://github.com/dlr-eoc/ukis-frontend-libraries/tree/feature-update) 

## Expected behavior
Upon calling `updateLayer`, the given layer should be updated. 

## Observations & attempted fixes
It initially seemed simple to just add another case to the method `updateLayerParamsWith`, which I have done in this branch.
**But** remarkably, now the updated layer disappears from  the map altogether. I could so far not figure out what is going wrong there. Note that calling `layer.setSource` works perfectly fine in a simple ol-only-application.

## Versions

**App**

* Angular: 10.0.14
* Node: v12.13.0
* Clarity: 4.0.0
* UKIS: HEAD

**Device:**

* Type: Laptop
* OS: Windows
* Browser Chrome
* Version 86.0.4240.193

**Comment by boeckMt** [comment]
@MichaelLangbein if you check the example in [route-example-events](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/demo-maps/src/app/route-components/route-example-events/route-map3.component.ts#L178), then you can see the update of a `CustomLayer`. In the [map-ol/component](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/feature-update/projects/map-ol/src/lib/map-ol.component.ts#L186) it checks then if the source has changed.
For our `VectorLayer` we do not have a update function, you have to recreate the layer with new data and add it again...

We have to check if some of the properties of the [VectorLayer](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/feature-update/projects/services-layers/src/lib/types/Layers.ts#L312) has changed and then check in [map-ol/component](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/map-ol/src/lib/map-ol.component.ts#L184) for the change and update the layer.

**Comment by MichaelLangbein** [comment]
> For our VectorLayer we do not have a update function, you have to recreate the layer with new data and add it again... We have to check if some of the properties of the VectorLayer has changed and then check in map-ol/component for the change and update the layer.

Absolutely right! I've tried to create such functionality [here](https://github.com/dlr-eoc/ukis-frontend-libraries/commit/39f05e2e631b05544cf61f18b745437fc9345c15#diff-fd3770e55b37963d6b96bb2476c5c8f75deaf8f2438b724a531bd2d419ac77aaR240). But now I'm having that strange issue with the layer disappearing on update. Investigation ongoing :)

**Comment by MichaelLangbein** [comment]
The issue has something to do with map-projection. Doesn't occur when map-projection is EPSG:4326. Now the error should be easy to find. Will push fix shortly.

**Comment by MichaelLangbein** [comment]
Issue has been fixed with commit [65c9bcf](https://github.com/dlr-eoc/ukis-frontend-libraries/commit/65c9bcf1ff44679a5740d4c550a4407939b9efc2)
