### ISSUE TITLE
InterpolationLayer - no renderDeclutter

### ISSUE THREAD

**Issue by voinSR** [dlr-eoc/ukis-frontend-libraries#57]
## Describe the bug

When you create an instance of InterpolationLayer, just like in the example shown in route-map4.component.ts

https://github.com/dlr-eoc/ukis-frontend-libraries/blob/128c9e311ffab9854bf2bb67193deb0fca4912a0/projects/demo-maps/src/app/route-components/route-example-custom-layers/route-map4.component.ts#L401

in the current master branch olMap complains that there is no renderDeclutter defined:

```
ERROR TypeError: this.getRenderer().renderDeclutter is not a function
    renderDeclutter BaseVector.js:226
    renderFrame Composite.js:135
    renderFrame_ PluggableMap.js:1402
    animationDelay_ PluggableMap.js:186
...
```

## To Reproduce

run mentioned above example

## Expected behavior
no error and working interpolation renderer

## Versions

**App**

* Node: [e.g. 4.15.0]
* UKIS and dependencies as in the master branch of this repo

**Device:**

* Type: DELL notebook
* OS: Windows 10
* Browser Chrome, Edge, Firefox

## Additional context
as a temporal workaround I use following after constructing the layer:

`InterpolationLayer.custom_layer.renderDeclutter = () => {};`

**Comment by MichaelLangbein** [comment]
Oooh, interesting!
`rendererDeclutter` has been added in the latest version of openlayers. @voinSR : your solution is actually the correct way to go!
The interpolation renderer does not require anything to actually happen in the `renderDeclutter` body. I'll add this to the renderer, so it's available with the next release. Thanks a lot!!

**Comment by MichaelLangbein** [comment]
PS: @voinSR , which version of Openlayers are you using?

**Comment by MichaelLangbein** [comment]
Issue handled with PR [59](https://github.com/dlr-eoc/ukis-frontend-libraries/pull/59)
