### ISSUE TITLE
@dlr-eoc/services-ogc is not exporting wms

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#66]
## Description

The services-ogc implements a lot of functionality https://github.com/dlr-eoc/ukis-frontend-libraries/tree/v7.2.0/projects/services-ogc/src/lib.
Currently only `owc`, `wps` and `wmts` are exported.
- https://github.com/dlr-eoc/ukis-frontend-libraries/blob/v7.2.0/projects/services-ogc/src/lib/services-ogc.module.ts
- https://github.com/dlr-eoc/ukis-frontend-libraries/blob/v7.2.0/projects/services-ogc/src/public-api.ts

At least the `wms` service should also be exported. Otherwise the not available in the npm package!

## Relevant Package
@dlr-eoc/services-ogc

**Comment by MichaelLangbein** [comment]
Alright!
With PR 70 WmsService is now exposed - together with the WPS-Types from utils-ogc/WPS.
