### ISSUE TITLE
Remove owc-control

### ISSUE THREAD

**Issue by MichaelLangbein** [dlr-eoc/ukis-frontend-libraries#77]
## Description
The project `dlr-eoc/owc-control` does not add much useful anymore. 
As discussed [here](https://github.com/dlr-eoc/ukis-frontend-libraries/pull/76#issuecomment-806769277), it used to be useful because it added a download-functionality in combination with saving current state as OWC-Json, but that download functionality is now also available in `@dlr-eoc/utils-browser`.

As such, this project can be removed.

- Does this change impact existing behaviors? If so how?
    - No, the project has not been used anywhere else in the frontend-libraries, and neither has it been used in any other projects derived from FELibs as far as I could find.

## Relevant Package
This feature request is for [@dlr-eoc/owc-control](https://github.com/dlr-eoc/ukis-frontend-libraries/packages)

**Comment by boeckMt** [comment]
Looks like the Package is used in https://github.com/dlr-eoc/ukis-frontend-libraries/blob/v7.3.1/projects/demo-maps/src/app/route-components/route-example-layers/route-map.component.html#L54

So if we remove it we should adjust the demo to reimplement the component https://github.com/dlr-eoc/ukis-frontend-libraries/blob/v7.3.1/projects/owc-control/src/lib/owc-control.component.ts

Maybe we can also add the logic of the component to sum function
```ts

 ngOnInit() {
    this.sub.push(this.layerSvc.getBaseLayers().subscribe((blays: Layer[]) => {
      this.baselayers = blays;
    }));
    this.sub.push(this.layerSvc.getOverlays().subscribe((olays: Layer[]) => {
      this.overlays = olays;
    }));
    this.layerSvc.getLayers().subscribe((llays: Layer[]) => {
      this.layers = llays;
    });
    this.sub.push(this.mapStateSvc.getExtent().subscribe((extent: TGeoExtent) => {
      this.extent = extent;
    }));
    this.sub.push(this.mapStateSvc.getMapState().subscribe((state: MapState) => {
      this.state = state;
    }));
  }

  onClickExport() {
    const id = 'myContext';
    const owc = this.owcSvc.generateOwsContextFrom(id, [...this.baselayers, ...this.overlays, ...this.layers], this.extent);
    this.downloadFile(owc, `${id}.json`);
  }
```
