### ISSUE TITLE
Dynamic component layer Input lost its Instance (Type)

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#80]
## Describe the bug
When using a [dynamic component](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/v7.3.0-next.3/projects/services-layers/src/lib/types/Layers.ts#L123) on the `layer-control`, the Input for `layer` lost its type/Instance.

## To Reproduce

1. Create a component for e.g.
```ts
new VectorLayer({
...
  action: {
    component: LayerTimeSliderComponent
  }
...
});
...
```
2. In this component try to test for the instance of the layer Input
```ts
...
// or other layer types e.g. CustomLayer, Layer...
if (this.layer instanceof VectorLayer) {

}
...
```
3. Then the layer is not of the same instance like it was bevor.

## Expected behavior
The layer in the component should have its original instance/type.

## Versions

**App**
* UKIS: [v7.3.0-next.3]

## Additional context

**Looks like the problem was introduced due to https://github.com/dlr-eoc/ukis-frontend-libraries/pull/71/commits/5fdf8f86fe71e230e13b2189f18af649a26d0033#diff-2423eff9797ad539c788180b6491bc59b135313011967ce6b2bce186538e5063 so the instance is only a object.**
```ts
...
const layerClone = Object.assign({}, layer);
...
```

**Comment by boeckMt** [comment]
> 
> ```ts
> ...
> const layerClone = Object.assign({}, layer);
> ...
> ```

found this https://2ality.com/2014/01/object-assign.html#2.3
```ts
// You can also use Object.assign() to (shallowly) clone an object:
var copy = Object.assign({ __proto__: obj.__proto__ }, obj);
```

**Comment by MichaelLangbein** [comment]
I've recently updated riesgos to use the frontend-libraries version 7.3.1. Since then, I have a similar error, where in @dlr-eoc/utils-maps/flattenLayers the code 
```  if (layer instanceof LayerGroup) { ```
no longer works. 

This is really pretty mysterious.

**Comment by boeckMt** [comment]
> I've recently updated riesgos to use the frontend-libraries version 7.3.1. Since then, I have a similar error, where in @dlr-eoc/utils-maps/flattenLayers the code
> ` if (layer instanceof LayerGroup) {`
> no longer works.
> 
> This is really pretty mysterious.

Do you use this function inside a dynamic component? 
I already have a fix for this Issue here, will push it soon.
