### ISSUE TITLE
dynamicPopup: getAttributes should be optional, but TypeError if not given

### ISSUE THREAD

**Issue by MichaelLangbein** [dlr-eoc/ukis-frontend-libraries#86]
## Describe the bug
```
TypeError: args.dynamicPopup.getAttributes is not a function
```
occurs when adding a dynamic popup to a ukis-`WmsLayer`

## To Reproduce
1. Code:
```
layer.popup = {
            dynamicPopup: {
                component: WindparkPopupComponent,
                // getAttributes: 
            }
        };
```
 
2. Error:
```
ERROR TypeError: args.dynamicPopup.getAttributes is not a function
    at MapOlService.createDynamicPopupComponent (dlr-eoc-map-ol.js:1443)
```

## Expected behavior
Should work without `getAttributes` - or, less optimal, make `getAttributes` required.

## Versions

**App**

* Angular: [11.2]
* UKIS: [7.3.1]

**Comment by boeckMt** [comment]
I think we should check for `getAttributes` in `createDynamicPopupComponent`


```ts
let attributes = args;
if(args.dynamicPopup.getAttributes && typeof args.dynamicPopup.getAttributes === 'function'){
  attributes = args.dynamicPopup.getAttributes(args);
}
```

**Comment by MichaelLangbein** [comment]
Being addressed by [PR 88](https://github.com/dlr-eoc/ukis-frontend-libraries/pull/88)
